# Generated by Django 4.2.2 on 2023-07-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='plataforma',
        ),
        migrations.AddField(
            model_name='juego',
            name='plataformas',
            field=models.ManyToManyField(to='m_tienda.plataforma'),
        ),
    ]
