# Generated by Django 4.2.2 on 2023-07-01 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m_tienda', '0002_remove_juego_plataforma_juego_plataformas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(null=True, upload_to='productos/')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_tienda.genero')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_tienda.plataforma')),
            ],
        ),
        migrations.RemoveField(
            model_name='juego',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='plataformas',
        ),
        migrations.DeleteModel(
            name='TarjetaRegalo',
        ),
        migrations.DeleteModel(
            name='Juego',
        ),
    ]
