# Generated by Django 4.2.2 on 2023-07-01 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m_tienda', '0004_marca_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='plataforma',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='m_tienda.marca'),
            preserve_default=False,
        ),
    ]
