# Generated by Django 4.2.2 on 2023-07-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_tienda', '0006_alter_producto_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='genero',
        ),
        migrations.AddField(
            model_name='producto',
            name='genero',
            field=models.ManyToManyField(blank=True, null=True, to='m_tienda.genero'),
        ),
    ]
