# Generated by Django 4.2.2 on 2023-07-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_tienda', '0009_remove_plataforma_marca_delete_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='genero',
            field=models.ManyToManyField(blank=True, to='m_tienda.genero'),
        ),
    ]
