# Generated by Django 4.2.2 on 2023-07-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_tienda', '0010_alter_producto_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='consola',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
