# Generated by Django 4.2.2 on 2023-07-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_tienda', '0011_producto_consola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='consola',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
