# Generated by Django 4.2.2 on 2023-07-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
